name: rebuild package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'arbritrary tag'
        required: true
        type: string

jobs:
  rebuild-package:
    runs-on: ubuntu-latest
    steps:
      - name: actually rebuild the package
        run: |
          write-output "rebuilding package for tag: $TAG"
	  echo "rebuilding package for tag: $TAG"
        env:
          TAG: ${{ inputs.tag }}
