name: rebuild package

on:
  workflow_dispatch:
    types: [remote_trigger]

jobs:
  rebuild-package:
    runs-on: ubuntu-latest
    steps:
      - name: actually rebuild the package
        run: |
          write-output "rebuilding package"
